# Generated by Django 6.0 on 2025-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jornada', models.CharField(max_length=50, verbose_name='Jornada')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('linea', models.CharField(max_length=100, verbose_name='Línea')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
    ]
