# Generated by Django 6.0 on 2025-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Permito de Protección'), ('OT', 'Otro')], default='CC', max_length=2, verbose_name='Tipo'),
        ),
    ]
