# Generated by Django 6.0 on 2025-12-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='linea',
            field=models.CharField(choices=[('AA', 'Asistencia Administrativa'), ('ISERC', 'Instalaciones eléctricas'), ('TPS', 'Programación de Software'), ('COM', 'Comunicación y medios audiovisuales'), ('ROB', 'Robótica'), ('BIO', 'Biotecnología'), ('DIS', 'Diseño multimedia'), ('OT', 'Otro')], default='OT', max_length=50, verbose_name='Línea'),
        ),
    ]
