# Generated by Django 6.0 on 2025-12-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_estudiante_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='acudiente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acudiente'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='eps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ocupacion_acudiente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación Acudiente'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tel2_acudiente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 2 Acudiente'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tel_acudiente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Acudiente'),
        ),
    ]
