# Generated by Django 6.0 on 2025-12-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_estudiante_acudiente_estudiante_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='parentesco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco Acudiente'),
        ),
    ]
