# Generated by Django 6.0 on 2025-12-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='jornada',
            field=models.CharField(choices=[('JM', 'Cédula de Ciudadanía'), ('JT', 'Tarjeta de Identidad')], max_length=50, verbose_name='Jornada'),
        ),
    ]
