# Generated by Django 6.0 on 2025-12-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_alter_estudiante_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='jornada',
            field=models.CharField(choices=[('JM', 'Jornada Mañana'), ('JT', 'Jornada Tarde')], default='JM', max_length=50, verbose_name='Jornada'),
        ),
    ]
