# Generated by Django 6.0 on 2025-12-26 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_alter_estudiante_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(choices=[('ALM', 'Almuerzo')], default='ALM', max_length=20),
        ),
    ]
