# Generated by Django 6.0 on 2026-06-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_alter_estudiante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='dependencia_practica',
            field=models.CharField(blank=True, choices=[('COORD_PRIM', 'Coordinación Primaria'), ('COORD_BACH', 'Coordinación Bachillerato'), ('ORIENTACION', 'Orientación'), ('SECRETARIA', 'Secretaría'), ('BIBLIOTECA', 'Biblioteca'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Dependencia de práctica'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='en_practica',
            field=models.BooleanField(default=False, verbose_name='¿Está haciendo práctica?'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_inicio_practica',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de práctica'),
        ),
    ]
