# Generated by Django 6.0.7 on 2026-07-22 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_estudiante_dependencia_practica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dependencia_practica',
            field=models.CharField(blank=True, choices=[('COORD_PRIM', 'Coordinación Primaria'), ('COORD_BACH', 'Coordinación Bachillerato'), ('ORIENTACION', 'Orientación'), ('SECRETARIA', 'Secretaría'), ('BIBLIOTECA', 'Biblioteca'), ('COORD_MED', 'Coordinación de Media'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Dependencia de práctica'),
        ),
    ]
