# Generated by Django 6.0.7 on 2026-07-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0015_estudiante_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='debe_cambiar_clave',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar contraseña al ingresar'),
        ),
    ]
