# Generated by Django 6.0.7 on 2026-07-27 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0016_estudiante_debe_cambiar_clave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocentePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(choices=[('AA', 'Asistencia Administrativa'), ('ISERC', 'Instalaciones eléctricas'), ('TPS', 'Programación de Software'), ('COM', 'Comunicación y medios audiovisuales'), ('ROB', 'Robótica'), ('BIO', 'Biotecnología'), ('DIS', 'Diseño multimedia'), ('OT', 'Otro')], max_length=50, verbose_name='Línea')),
                ('jornada', models.CharField(choices=[('JM', 'Jornada Mañana'), ('JT', 'Jornada Tarde')], max_length=50, verbose_name='Jornada')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Docente — grupo asignado',
                'verbose_name_plural': 'Docentes — grupos asignados',
            },
        ),
        migrations.CreateModel(
            name='RegistroPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('bloque', models.PositiveSmallIntegerField(choices=[(1, 'Bloque 1'), (2, 'Bloque 2')], default=1, verbose_name='Bloque')),
                ('estado', models.CharField(choices=[('F', 'Falla'), ('A', 'Asistió'), ('R', 'Llegada tarde'), ('E', 'Evasión de clase'), ('EX', 'Excusa justificada'), ('U', 'Uniforme incompleto')], max_length=2, verbose_name='Estado')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_planilla', to='estudiantes.estudiante')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_planilla_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de planilla',
                'verbose_name_plural': 'Registros de planilla',
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'fecha', 'bloque'), name='unico_estudiante_fecha_bloque')],
            },
        ),
    ]
