# Generated by Django 6.0.7 on 2026-07-31 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0017_docenteperfil_registroplanilla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docenteperfil',
            name='curso',
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(choices=[('AA', 'Asistencia Administrativa'), ('ISERC', 'Instalaciones eléctricas'), ('TPS', 'Programación de Software'), ('COM', 'Comunicación y medios audiovisuales'), ('ROB', 'Robótica'), ('BIO', 'Biotecnología'), ('DIS', 'Diseño multimedia'), ('OT', 'Otro')], max_length=50, verbose_name='Línea')),
                ('jornada', models.CharField(choices=[('JM', 'Jornada Mañana'), ('JT', 'Jornada Tarde')], max_length=50, verbose_name='Jornada')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la actividad')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad calificable',
                'verbose_name_plural': 'Actividades calificables',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota (0.0 a 5.0)')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='estudiantes.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_actividades', to='estudiantes.estudiante')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de actividad',
                'verbose_name_plural': 'Notas de actividades',
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'actividad'), name='unica_nota_estudiante_actividad')],
            },
        ),
    ]
