# Generated by Django 6.1 on 2026-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0018_remove_docenteperfil_curso_actividad_notaactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('F', 'Falla'), ('A', 'Asistió'), ('R', 'Llegada tarde'), ('E', 'Evasión de clase'), ('EX', 'Excusa justificada'), ('U', 'Uniforme incompleto')], max_length=2, unique=True, verbose_name='Estado')),
                ('puntos', models.IntegerField(verbose_name='Puntos (use un número negativo para descontar)')),
            ],
            options={
                'verbose_name': 'Puntos por estado de asistencia',
                'verbose_name_plural': 'Configuración de puntos por asistencia',
                'ordering': ['estado'],
            },
        ),
    ]
