# Generated by Django 6.1 on 2026-08-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0020_sembrar_configuracionpuntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionpuntos',
            name='puntos',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntos (use un número negativo para descontar; admite decimales, ej: -0.5)'),
        ),
    ]
