# Generated by Django 6.1 on 2026-08-25 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0021_alter_configuracionpuntos_puntos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registroplanilla',
            name='unico_estudiante_fecha_bloque',
        ),
        migrations.AddConstraint(
            model_name='registroplanilla',
            constraint=models.UniqueConstraint(fields=('estudiante', 'fecha', 'bloque', 'estado'), name='unico_estudiante_fecha_bloque_estado'),
        ),
    ]
