# Generated by Django 6.1.1 on 2026-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0022_remove_registroplanilla_unico_estudiante_fecha_bloque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='documento',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Documento'),
        ),
    ]
