# Generated by Django 6.1.1 on 2026-09-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0023_alter_estudiante_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.CharField(blank=True, choices=[('10', '10°'), ('11', '11°')], db_index=True, help_text='Se usa para filtrar por 10°/11° sin depender del formato del código de curso.', max_length=5, verbose_name='Grado'),
        ),
    ]
