# Generated by Django 6.1.1 on 2026-09-10 20:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0025_backfill_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplanilla',
            name='puntos_aplicados',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Puntos que tenía configurado este estado en el momento en que se registró. Queda fijo aquí a propósito: si luego se cambia la configuración de puntos del admin, las definitivas ya calculadas de meses anteriores NO cambian retroactivamente.', max_digits=5, verbose_name='Puntos aplicados'),
        ),
    ]
