# Generated by Django 6.1.1 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0028_alter_estudiante_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='tipo',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PPT', 'Permiso por Protección Temporal'), ('OT', 'Otro')], default='CC', max_length=5, verbose_name='Tipo'),
        ),
    ]
